name: Build and Upload OpenWrt Passwall Packages

on:
  push:
    branches:
      - main
  workflow_dispatch: # قابلیت اجرای دستی

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    env:
      SFTP_HOST: static.115.193.75.5.clients.your-server.de
      REPO_URL: https://github.com/peditx/openwrt-passwall-packages.git

    steps:
    # مرحله 1: کلون کردن ریپازیتوری
    - name: Checkout Repository
      uses: actions/checkout@v3

    # مرحله 2: تعریف معماری‌های OpenWrt
    - name: Define Architectures
      id: architectures
      run: |
        echo "architectures=x86_64 arm_cortex-a7 arm_cortex-a9 arm_cortex-a53 arm_cortex-a72 aarch64_cortex-a53 aarch64_cortex-a72 aarch64_generic i386 mipsel_24kc mipsel_74kc mips_24kc mips_mips32 mips_mips64r2 powerpc_8540 powerpc_970 sparc64" >> $GITHUB_ENV

    # مرحله 3: ایجاد پوشه برای هر معماری و کپی فایل‌ها
    - name: Organize Makefiles
      run: |
        mkdir -p makefiles
        for arch in $architectures; do
          mkdir -p "makefiles/$arch"
          if [ -d "./package/$arch" ]; then
            cp -r "./package/$arch"/* "makefiles/$arch/"
          else
            echo "Warning: No files found for $arch, skipping."
          fi
        done

    # مرحله 4: ایجاد فایل‌های package.gz و package.manifest
    - name: Create Metadata Files
      run: |
        for arch in $architectures; do
          echo "Creating package.gz and package.manifest for $arch"
          tar -czf "makefiles/$arch/package.gz" -C "makefiles/$arch" .
          echo "Manifest for $arch packages" > "makefiles/$arch/package.manifest"
        done

    # مرحله 5: آپلود فایل‌ها به SFTP
    - name: Upload to SFTP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ env.SFTP_HOST }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        source: ./makefiles/*
        target: /path/to/destination
