name: Build and Upload OpenWrt Packages

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      # 1. دریافت ریپازیتوری
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. نصب ابزارهای مورد نیاز برای کامپایل
      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev gawk git ccache gettext zlib1g-dev libssl-dev xsltproc file unzip wget python3

      # 3. دانلود و نصب SDK برای معماری‌های مختلف
      - name: Download and Setup OpenWrt SDK
        run: |
          architectures="aarch64_cortex-a53 aarch64_cortex-a72 aarch64_generic arm_arm1176jzf-s arm_cortex-a7_neon-vfpv4 arm_cortex-a9 arm_cortex-a15_neon-vfpv4 arm_cortex-a53_neon-vfpv4 arm_cortex-a72_neon-vfpv4 arm_xscale i386_generic mips_24kc mips_mips32 mipsel_24kc mipsel_mips32 powerpc_464fp powerpc_8540 x86_64"
          mkdir -p sdk
          for arch in $architectures; do
            wget -q "https://downloads.openwrt.org/releases/23.05.0/targets/${arch}/sdk.tar.xz" -O "sdk/$arch-sdk.tar.xz"
            mkdir -p "sdk/$arch"
            tar -xf "sdk/$arch-sdk.tar.xz" -C "sdk/$arch" --strip-components=1
          done

      # 4. کامپایل فایل‌های میک برای هر معماری
      - name: Build Packages for All Architectures
        run: |
          architectures="aarch64_cortex-a53 aarch64_cortex-a72 aarch64_generic arm_arm1176jzf-s arm_cortex-a7_neon-vfpv4 arm_cortex-a9 arm_cortex-a15_neon-vfpv4 arm_cortex-a53_neon-vfpv4 arm_cortex-a72_neon-vfpv4 arm_xscale i386_generic mips_24kc mips_mips32 mipsel_24kc mipsel_mips32 powerpc_464fp powerpc_8540 x86_64"
          for arch in $architectures; do
            echo "Building for architecture: $arch"
            pushd sdk/$arch
            make package/feeds/packages/compile V=s
            popd
          done

      # 5. بسته‌بندی خروجی‌ها
      - name: Create Metadata and Package Files
        run: |
          architectures="aarch64_cortex-a53 aarch64_cortex-a72 aarch64_generic arm_arm1176jzf-s arm_cortex-a7_neon-vfpv4 arm_cortex-a9 arm_cortex-a15_neon-vfpv4 arm_cortex-a53_neon-vfpv4 arm_cortex-a72_neon-vfpv4 arm_xscale i386_generic mips_24kc mips_mips32 mipsel_24kc mipsel_mips32 powerpc_464fp powerpc_8540 x86_64"
          for arch in $architectures; do
            mkdir -p output/$arch
            cp -r sdk/$arch/bin/packages/* output/$arch/

            # ایجاد package.gz
            tar --warning=no-file-changed -czf "output/$arch/package.gz" -C "output/$arch" .

            # ایجاد package.manifest
            echo "Manifest for $arch packages" > "output/$arch/package.manifest"
          done

      # 6. آپلود به سرور SFTP
      - name: Upload to SFTP Server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: static.115.193.75.5.clients.your-server.de
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          source: output/
          target: /var/www/html/passwall-packages/
